### ISSUE TITLE
This package does not exist in the NPM repository

### ISSUE THREAD

**Issue by dengbupapapa** [webpack-contrib/install-webpack-plugin#237]
hi,This package does not exist in the NPM repository, and the cloned git package does not work properly

**Comment by snitin315** [comment]
Hi @dengbupapapa , this packages is yet to be released on npm. 

What is not working properly? can you provide more context with reporducible repo?

**Comment by dengbupapapa** [comment]
> 嗨@dengbupapapa，这个包还没有在 npm 上发布。
> 
> 什么工作不正常？你能提供更多关于可重复存储的上下文吗？
Here's my example: https://github.com/dengbupapapa/webpack5-install-webpack-plugin-example/tree/main
The WebPack version used is ^5.46.0。Error is as follows：
E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208
            return next();
                   ^

TypeError: next is not a function
    at InstallPlugin.resolveModule (E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208:20)
    at _next0 (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:30:1)
    at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by xeroxstar** [comment]
I cant install it either, it's give me an 404 error when i run `npm install --save-dev install-webpack-plugin`
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/install-webpack-plugin - Not found
npm ERR! 404
npm ERR! 404  'install-webpack-plugin@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by JaxXu** [comment]
> > Hi @dengbupapapa , this packages is yet to be released on npm.
> > What is not working properly? can you provide more context with reporducible repo?
> 
> Here's my example: https://github.com/dengbupapapa/webpack5-install-webpack-plugin-example/tree/main
> `$ node config.js`
> The WebPack version used is ^5.46.0。Error is as follows：
> E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208
> return next();
> ^
> 
> TypeError: next is not a function
> at InstallPlugin.resolveModule (E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208:20)
> at _next0 (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :8:1)
> at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :30:1)
> at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\Resolver.js:410:5
> at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :16:1)
> at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:41:15
> at processTicksAndRejections (internal/process/task_queues.js:81:21)

@snitin315 
Webpack 5.51.1
I have the same problem 
`next` is not a function , but an object like this
```
{
  "fileDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "contextDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "missingDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "stack": {}
}
```

**Comment by JaxXu** [comment]
> > Hi @dengbupapapa , this packages is yet to be released on npm.
> > What is not working properly? can you provide more context with reporducible repo?
> 
> Here's my example: https://github.com/dengbupapapa/webpack5-install-webpack-plugin-example/tree/main
> `$ node config.js`
> The WebPack version used is ^5.46.0。Error is as follows：
> E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208
> return next();
> ^
> 
> TypeError: next is not a function
> at InstallPlugin.resolveModule (E:\dev\example\webpackConfigExample\node_modules\install-webpack-plugin\src\plugin.js:208:20)
> at _next0 (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :8:1)
> at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :30:1)
> at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\Resolver.js:410:5
> at eval (eval at create (E:\dev\example\webpackConfigExample\node_modules\tapable\lib\HookCodeFactory.js:33:10), :16:1)
> at E:\dev\example\webpackConfigExample\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:41:15
> at processTicksAndRejections (internal/process/task_queues.js:81:21)

@snitin315 
Webpack 5.51.1
I have the same problem 
`next` is not a function , but an object like this
```
{
  "fileDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "contextDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "missingDependencies": {
    "_set": {},
    "_toMerge": {},
    "_toDeepMerge": [],
    "_needMerge": false,
    "_deopt": false
  },
  "stack": {}
}
```

**Comment by JBreit** [comment]
This worked for me:

`npm i -D https://github.com/webpack-contrib/install-webpack-plugin.git`
